<Config>
  <LoginWindow>
    <MatrixID>mkkim</MatrixID>
    <MatrixPW>1234</MatrixPW>
    <SecID>sky09376</SecID>
    <SecPW>1230</SecPW>
    <CertPW></CertPW>
    <TradeMode>VT</TradeMode>
  </LoginWindow>
  <CertWindow>
    <Title>인증서 선택  (Ver 9.8.0.2)  </Title>
    <OKCaption>인증서 선택(확인)</OKCaption>
  </CertWindow>
  <MainWindow>
    <Title>CME3</Title>
    <FileName></FileName>
    <OrderCount>1</OrderCount>
    <AccountNo>2582601002</AccountNo>
    <AccountPW>1230</AccountPW>
    <EMail>worldia@naver.com</EMail>
  </MainWindow>
</Config>
