unit FNMatrixConst;

interface

const
  NOT_VALUE: Double = -1.0E38;
  MIN_VALUE: Double = -1.0E100;
  MAX_VALUE: Double = 1.0E100;

const

  M_X_SIGNAL = 0;
  M_X_REALPRICE = 1;
  M_X_SIGNAL_TP = 2;

  M_MERGE_LINE_SYSTEMNO = 0; // 시스템의 번호
  M_MERGE_LINE_HIGHPRICE = 1; // 실물가격
  M_MERGE_LINE_LOWPRICE = 2; // 실물가격
  M_MERGE_LINE_REALPRICE = 3; // 실물가격
  M_MERGE_LINE_VOLUME = 4; // 거래량
  M_MERGE_LINE_SIGNAL1 = 5; // 1차신호
  M_MERGE_LINE_PROFIT1 = 6; // 1차신호의 누적수익
  M_MERGE_LINE_PROFIT1_H = 7; // 1차신호의 누적수익
  M_MERGE_LINE_PROFIT1_L = 8; // 1차신호의 누적수익
  M_MERGE_LINE_PROFIT1_STOP = 9; // 1차신호의 거래정지 여부
  M_MERGE_LINE_SIGNAL2 = 10; // 2차신호
  M_MERGE_LINE_PROFIT2 = 11; // 2차신호의 누적수익
  M_MERGE_LINE_SIGNAL3 = 12; // 3차신호
  M_MERGE_LINE_PROFIT3 = 13; // 3차신호의 누적수익

  M_MATRIX_LINE_REALPRICE = 0;
  M_MATRIX_LINE_VALUE = 1;
  M_MATRIX_LINE_VALUE_MA0 = 2;
  M_MATRIX_LINE_VALUE_MA1 = 3;
  M_MATRIX_LINE_VALUE_MA2 = 4;
  M_MATRIX_LINE_MAXVALUE = 5;
  M_MATRIX_LINE_TR_INDEX = 6;
  M_MATRIX_LINE_TR_ENTER_VALUE = 7;
  M_MATRIX_LINE_TR_EXIT_VALUE = 8;
  M_MATRIX_LINE_TR_VALUE = 9;
  M_MATRIX_LINE_TR_MAXVALUE = 10;
  M_MATRIX_LINE_TR_EXITI_NDEX = 11;
  M_MATRIX_LINE_TR_STOP_TYPE = 12;
  M_MATRIX_LINE_FINALVALUE = 13;
  M_MATRIX_LINE_ENTERSTEP = 14;
  M_MATRIX_LINE_NOTR_LOWESTVALUE = 15;
  M_MATRIX_LINE_INTERVALUE1 = 16;
  M_MATRIX_LINE_TRADE_STOP = 17;
  M_MATRIX_LINE_CANTRADE01 = 18;
  M_MATRIX_LINE_CANTRADE02 = 19;
  M_MATRIX_LINE_CANTRADE03 = 20;
  M_MATRIX_LINE_TR_VALUE03 = 21;
  M_MATRIX_LINE_TR_EXIT_VALUE03 = 22;

  M_MATRIX_VLINE_VOLUME = 0;

type
  CFNMatrixConst = class
  public const
    CHART_DRAW_YLABEL_WIDTH = 50;
    CHART_DRAW_XLABEL_HEIGHT = 13;
    CHART_DRAW_YBOUNDARY_OFFSET = 2;
    CHART_DRAW_YLABEL_WIDTH2 = 50;
    CHART_DRAW_XLABEL_HEIGHT2 = 13;
    CHART_DRAW_YBOUNDARY_OFFSET2 = 2;

    CHART_INTERHEIGHT = 0;
    CHART_NORMAL = 0;
    CHART_MAMUL = 3;
    LINESERIES_PRICE = 0;
    LINESERIES_CLOSE = 1;
    LINESERIES_MA = 2;
    LINESERIES_ILMOK = 3;
    LINESERIES_BB = 4;
    LINESERIES_ENVELOPE = 5;
    LINESERIES_SAR = 6;
    LINESERIES_NET = 7;
    LINESERIES_VOLUME = 9;
    LINESERIES_MACD = 10;
    LINESERIES_ADX = 11;
    LINESERIES_DMI = 12;
    LINESERIES_RSI = 13;
    LINESERIES_OBV = 14;
    LINESERIES_FASTSTC = 15;
    LINESERIES_SLOWSTC = 16;
    LINESERIES_SONAR = 17;
    LINESERIES_PMAO = 18;
    LINESERIES_TRIX = 19;
    LINESERIES_PSY = 20;
    LINESERIES_CCI = 21;
    LINESERIES_VR = 22;
    LINESERIES_WILLIAM = 23;
    LINESERIES_ROC = 24;
    LINESERIES_LRL = 25;
    LINESERIES_VMAO = 26;
    LINESERIES_BBWIDTH = 27;
    LINESERIES_ATR = 28;
    LINESERIES_COMPARECLOSE = 32;

    LINESERIES_PRICE_MA_CROSS_SIGNAL = 40;
    LINESERIES_MA_CROSS_SIGNAL = 41;
    LINESERIES_MACD_CROSS_SIGNAL = 42;
    LINESERIES_SSTC_CROSS_SIGNAL = 43;
    LINESERIES_FSTC_CROSS_SIGNAL = 44;
    LINESERIES_RSI_CROSS_SIGNAL = 45;
    LINESERIES_ADX_CROSS_SIGNAL = 46;
    LINESERIES_WILLIAMSR_CROSS_SIGNAL = 47;
    LINESERIES_SONA_CROSS_SIGNAL = 48;
    LINESERIES_TRIX_CROSS_SIGNAL = 49;
    LINESERIES_NMA_TREND_SIGNAL = 50;
    LINESERIES_WMA_TREND_SIGNAL = 51;
    LINESERIES_XMA_TREND_SIGNAL = 52;

    LINESERIES_MATRIX = 53;

    PRICE_OPEN = 0;
    PRICE_HIGH = 1;
    PRICE_LOW = 2;
    PRICE_CLOSE = 3;
    SAMSUN_CLOSE = 0;
    SAMSUN_HIGH = 1;
    SAMSUN_LOW = 2;
    SAMSUN_SIGN = 3;
    SAMSUN_VALUE = 4;
    PCLOSE = 0;
    PSIGN = 1;
    PX = 2;
    PY = 3;

    PF_CLOSE = 0;
    PF_SIGN = 1;
    PF_X = 2;
    PF_Y = 3;

    MAMUL_HIGH = 0;
    MAMUL_LOW = 1;
    MAMUL_VOLUME = 2;
    MAMUL_VRATOR = 3;

    MAX_OVERLAY_COUNT = 6;
    MAX_INDICATOR_COUNT = 10;
    MAX_SIGNAL_COUNT = 10;

    COLOR_SET_BLACK = 0;
    COLOR_SET_WHITE = 1;

  end;

implementation

end.
